### ISSUE TITLE
GoogleHttpAdapter - Documentation

### ISSUE THREAD

**Issue by jnutkins** [BotBuilderCommunity/botbuilder-community-dotnet#128]
Hi,

The documentation for the Google Adapter for MVC doesn't appear to be correct:

```
services.AddSingleton<IGoogleHttpAdapter>((sp) =>
	{
	    var googleHttpAdapter = new GoogleHttpAdapter(validateRequests: true)
	    {
	        OnTurnError = async (context, exception) =>
	        {
	            await context.SendActivityAsync("Sorry, something went wrong");
	        },
	        ShouldEndSessionByDefault = true,
	    };
	
	    return googleHttpAdapter;
	});
```
As it doesn't have a parameter called 'validateRequests'. I've tried with the HttpContextAccessor but seem to get 'Object Reference not set to an instance of an Object' errors. I have a feeling I have set this part up incorrectly.

**Comment by JohnRobertGreen** [comment]
Having the same issue. Injecting the context accessor works. Then I get errors which appear to be due to the originalDetectIntentRequest being empty and lots of null object errors. 

Fulfillment request is:
{
  "responseId": "7e705056-6da6-42e7-a9bd-3b4dc5f63d4f-712767ed",
  "queryResult": {
    "queryText": "whats my balance",
    "parameters": {},
    "allRequiredParamsPresent": true,
    "fulfillmentText": "Asking Ulti your question",
    "fulfillmentMessages": [
      {
        "text": {
          "text": [
            "Asking Ulti your question"
          ]
        }
      }
    ],
    "intent": {
      "name": "projects/ultibot1/agent/intents/c9f52372-b544-4962-9fb5-42985d012e69",
      "displayName": "Default"
    },
    "intentDetectionConfidence": 1,
    "languageCode": "en"
  },
  "originalDetectIntentRequest": {
    "payload": {}
  },
  "session": "projects/ultibot1/agent/sessions/a2bb9da1-c24d-3d06-2d23-7aa340666fa0"
}

**Comment by marcasmar94** [comment]
Any updates?

**Comment by mirkon90** [comment]
same issue here @garypretty @arafattehsin any news or clues?

**Comment by JohnRobertGreen** [comment]
Its been a while since I looked at this. My recollection is that when you use the "Try it now" feature on the DialogFlow, Fulfilment page your bot will receive the fulfilment request I posted above and the bot google adapter throws a bunch of errors. However when you test via the "See how it works in Google Assistant" link (just below the Try it now textbox) your bot will receive a fulfilment request structured as expected by the google adapter. Hope that helps.

**Comment by garypretty** [comment]
I have now made the preview of the updated / refactored Google Adapter available via MyGet with all new documentation - you can find the updated docs, which detail how to get access to the preview package here -> https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/feature/google-adapter-refactor/libraries/Bot.Builder.Community.Adapters.Google/README.md

Please let me know if you have any feedback on the docs.

**Comment by garypretty** [comment]
Closing this issue as the new docs are now in place - they will go out as the preview moves to GA.
