### ISSUE TITLE
FormFlow State doesn't properly reset on FormCanceledException

### ISSUE THREAD

**Issue by mdrichardson** [BotBuilderCommunity/botbuilder-community-dotnet#146]
This stems from @paul198204's (@EricDahlvang: this is Praveen) issue where basically:

1. User starts FormFlow Dialog
2. User says "quit" and bot cancels all dialogs
3. User attempts to restart FormFlow Dialog, but instead continues where they left off

Not being familiar with FormFlow, I'm posting this here for additional help.

My guess is that the `else` clause [from here](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/3f3c7b8f2a30d348a388d5412bd97d3a46587ade/libraries/Bot.Builder.Community.Dialogs.FormFlow/FormDialog.cs#L525) should call `_formState.Reset()`:

```csharp
            catch (Exception inner)
            {
                if (!(inner is FormCanceledException<T>))
                {
                    throw new FormCanceledException<T>(inner.Message, inner)
                    {
                        LastForm = _state,
                        Last = _form.Steps[_formState.Step].Name,
                        Completed = (from step in _form.Steps
                                     where _formState.Phase(_form.StepIndex(step)) == StepPhase.Completed
                                     select step.Name).ToArray()
                    };
                }
				// HERE
                else
                {
                    throw;
                }
            }
        }
```

I also considered recommending that the user call `Reset()` manually since [it's public in FormState](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Dialogs.FormFlow/FormState.cs#L62). However, they'd like to call it from outside of `FormDialog` but [`FormDialog` has `_formState` private](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/3f3c7b8f2a30d348a388d5412bd97d3a46587ade/libraries/Bot.Builder.Community.Dialogs.FormFlow/FormDialog.cs#L126).

There's likely a way to do this, but again, I'm not very familiar with FormFlow.

**Comment by paul198204** [comment]
Adding to it, I guess it should be called even in form Complete case

**Comment by paul198204** [comment]
I did verify that, if we do reset, it looks to be working :). I also noted that in the BeginDialogAsync of FormDialog.cs file, there is no formState.reset() call which is causing issues while bringing up the same form 2nd time (after completion of form 1st time with out any errors). I see only below instead of reset call

public async override Task<DialogTurnResult> BeginDialogAsync(DialogContext outerDc, object options = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (this._entities.Any())
            {
                var inputs = new List<Tuple<int, string>>();
                var entityGroups = (from entity in this._entities group entity by entity.Role ?? entity.Type);
                foreach (var entityGroup in entityGroups)
                {
                    var step = _form.Step(entityGroup.Key);
                    if (step != null)
                    {
                        var builder = new StringBuilder();
                        var first = true;
                        foreach (var entity in entityGroup)
                        {
                            if (first)
                            {
                                first = false;
                            }
                            else
                            {
                                builder.Append(' ');
                            }
                            builder.Append(entity.Entity);
                        }
                        inputs.Add(Tuple.Create(_form.StepIndex(step), builder.ToString()));
                    }
                }
                if (inputs.Any())
                {
                    // Descending because last entry is first processed
                    _formState.FieldInputs = (from input in inputs orderby input.Item1 descending select input).ToList();
                }
            }
            await SkipSteps();
            _formState.Step = 0;
            _formState.StepState = null;

**Comment by EricDahlvang** [comment]
It seems reasonable to clear the state on begin, on complete, on cancel, and when the dialog stack is cancelled (is that an overridable method or event in ComponentDialog?)

**Comment by paul198204** [comment]
_formState looks to be local (Private) to FormDialog and not exposed outside. It would be great if you also verify Reset is actually resetting all the formstate internal data (Like reset steps state etc...)

**Comment by EricDahlvang** [comment]
When a ComponentDialog is cancelled, EndDialogAsync is called with DialogReason.CancelCalled: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs#L216

This could be overridden in FormDialog https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Dialogs.FormFlow/FormDialog.cs and  the state cleared there too.

**Comment by garypretty** [comment]
@EricDahlvang Do you have any bandwidth over the next couple of weeks to take a look at the FormFlow issues?  I am reviewing / taking action on the other issues in the repo as well as hoping to get the docs / samples refreshed as well.

**Comment by garypretty** [comment]
@EricDahlvang that's totally fine. Just looking to assign it if I can. It can totally wait a couple of weeks. I'm in the same boat. 😀👍

**Comment by garypretty** [comment]
Quick update on this - we are hoping to get to this issue in the first half of November if nobody picks it up in the meantime.

**Comment by EricDahlvang** [comment]
Was this fixed with: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/commit/7cf59209e2898f277c1ae506050b01247c6dea52#diff-ea7f00989b869c83f816ed6cf9080c85 ?

**Comment by garypretty** [comment]
@EricDahlvang That PR resets the state on begin but, as per your comment above, I don't know if we need to call it anywhere else?  Certainly calling it on begin should resolve the issue of reusing the same dialog a second time I think. I've not had time to look into it - knowing this code a little better than I do, what's your take?

**Comment by v-kydela** [comment]
@EricDahlvang - Why does that only reset `_formState` and not `_state`? Perhaps it would have been better to use my issue to track this problem: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/157

**Comment by garypretty** [comment]
@EricDahlvang @v-kydela sorry both. Trying to triage and progress issues whilst on vacation 😁 hence I missed the reasoning for having a separate issue. Happy to reopen @v-kydela if we think that's the best approach. Or maybe we can agree an approach between us and ensure it is documented in a single issue to reduce the noise?

**Comment by paul198204** [comment]
Hi,Sorry for late reply on this. This PR should fix the issue (using form steps state on next turns after form closing) with _formState refresh and we may need some other fix to address _state (using the dialog instance state on next turn after form close) refresh issue.ThanksPraveen V Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Gary Pretty <notifications@github.com> Date: 11/29/19  9:52 AM  (GMT-08:00) To: BotBuilderCommunity/botbuilder-community-dotnet <botbuilder-community-dotnet@noreply.github.com> Cc: paul198204 <paul1982.04@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [BotBuilderCommunity/botbuilder-community-dotnet] FormFlow State
  doesn't properly reset on FormCanceledException (#146) @EricDahlvang @v-kydela sorry both. Trying to triage and progress issues whilst on vacation 😁 hence I missed the reasoning for having a separate issue. Happy to reopen @v-kydela if we think that's the best approach. Or maybe we can agree an approach between us and ensure it is documented in a single issue to reduce the noise?



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/146?email_source=notifications\u0026email_token=ADF2ZABV534VYOSNG6DLIVDQWFJHXA5CNFSM4ISFSE4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFPLMDQ#issuecomment-559855118",

"url": "https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/146?email_source=notifications\u0026email_token=ADF2ZABV534VYOSNG6DLIVDQWFJHXA5CNFSM4ISFSE4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFPLMDQ#issuecomment-559855118",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by EricDahlvang** [comment]
I am of the opinion we should close this issue until we have other complaints.  There are a lot of people using this library as-is, and they do not seem to behaving problems.  If we get other complaints, it might become worth the risk of updating.

**Comment by garypretty** [comment]
Agreed. Closing.
