### ISSUE TITLE
AdaptiveCardPrompt Bot Framework 4.0

### ISSUE THREAD

**Issue by rvinothrajendran** [BotBuilderCommunity/botbuilder-community-dotnet#155]
AdaptiveCardPrompt 
Natively, Adaptive cards events (like submit or cancel button) does not work in the Prompt dialog. I have written the code to handle the Adaptive cards events in the prompt dialog. If you accept this idea, will create the PR and submit the code.

Thank you
-Vinoth.

**Comment by v-kydela** [comment]
You might be interested to know that others have been working on much the same thing: https://github.com/microsoft/botframework-sdk/issues/5396

There's no need to be disappointed about the duplicated work, though. It makes sense to have choices when it comes to this sort of thing. I encourage you to submit the code because I'd like to see what you've done. The more the merrier!

**Comment by rvinothrajendran** [comment]
Thanks @v-kydela , I have checked #5396 it has lot features mine just overwrite the Prompt class and return the Json object 
Thank you.

**Comment by v-kydela** [comment]
@rvinothrajendran - I should mention that it's currently possible to use an Adaptive Card with a text prompt if you replace the turn context's incoming activity's text with the serialized JSON from the submit action.
