### ISSUE TITLE
Example of using the "Bot Framework Emulator" with AlexaAdapter

### ISSUE THREAD

**Issue by pdkn** [BotBuilderCommunity/botbuilder-community-dotnet#187]
Is it possible to use the Emulator to debug an AlexaAdapter bot? I'm currently in local development, using ngrok endpoint on AWS in the Alexa Skill. The response is error'ing with a log statement "the application completed without reading the entire request body." I'd like to use the Emulator with a fake request to test the logic and set breakpoints to step through the code. Thanks

**Comment by garypretty** [comment]
@pdkn The emulator won't be the right choice here, but you can achieve what you are looking for.
My recommendation would be the following. 

1. Download a tool like PostMan so that you can post directly to your Alexa endpoint. e.g. '/api/alexa'
2. Grab an example request JSON from the Alexa simulator.
3. In your adapter settings, set **ValidateIncomingRequests** to false - this will ensure the bot doesn't try and validate requests as coming from the Alexa skills service.
4. Post the example JSON using PostMan directly at your bot and you should be able to debug from there.

**Comment by pdkn** [comment]
Thanks 🙏@garypretty I'll investigate

**Comment by garypretty** [comment]
Thanks @pdkn. I will close this for now, but please re-open if you get stuck or need any other assistance. 👍
