### ISSUE TITLE
Public facing standup hosted by the product team?

### ISSUE THREAD

**Issue by cleemullins** [BotBuilderCommunity/botbuilder-community-dotnet#25]
Hello BotBuilderCommunity,

Within the product team, we've come to an agreement to do public facing "standup" on a regular basis. I wanted to reach out to this community and solicit some input:

1. **Cadence.** What frequency would work well? Once a month? Once a week? 
2. **Technology.** The two obvious choices are SfB or a Teams meeting and post the link. We would probably include video + audio as part of this. Any other technology candidates? (Streamed on Youtube? FB Live? Something else?)
3. **Agenda.** This is where we would like the most help. What *should* we discuss here? Open PR's across product (or community) repos? Roadmaps? We can go through our [DCR list](https://github.com/Microsoft/BotBuilder/issues?q=is%3Aissue+is%3Aopen+label%3ADCR). 
4. **Where To Post?** Where/how should we post this?

Note: The [ASP.Net Core](https://github.com/aspnet/AspNetCore) team does this. From their [readme](https://github.com/aspnet/AspNetCore/blob/master/README.md):
    * [Community Standup](http://live.asp.net): The community standup is held every week and streamed live to YouTube. You can view past standups in the linked playlist.

I don't think we're ready to jump quite that high yet, but it seems a great goal. 

Your thoughts? 

//Chris

**Comment by garypretty** [comment]
@cleemullins This sounds like a great idea and I support it wholeheartedly. Here are my thoughts;

Once a month feels like it will be about right (I think once a week is too much for starting on something like this).  I might be that something in between works well given the speed things are moving though at times.

I think SFB or Teams would work well - I am just not sure if that actually excludes some people?  I know that Teams is free to use now, so I guess people can get it if they need it.  Given that it is so simple to get started with these platforms, start there and then see what traction you get before moving somewhere else which is going to take more thought. That would be my take.

In terms of an agenda I think the DCR list makes sense, but maybe also provide an overview of any major decisions / changes made since the last standup and highlight what is coming over the next period.  You could also allow community / team members to suggest agenda items.

I think this could be a great place to drive content between our repos too. If anything gets discussed that it is agreed doesn't fit within the SDK repo, perhaps we can add it to our backlog.

**Comment by cloudguy-pro** [comment]
Hey guys,
I love to hear what you are planning.
I follow a quite similar approach from Vesa Juvonen (PM SharePoint Dev) -> https://docs.microsoft.com/en-us/sharepoint/dev/community/community#community-calls he is doing bi-weekly calls.
I think for starting once in a month would be sufficient. Teams is a great platform for hosting that as we got audio/video and desktop sharing and the quality is so much better compared to SfB.

I think I speak for all of us core BotBuilderCommunity members if I say that if you need assistance doing this we will be in.
It would be cool if we would have the chance to present some stuff we are working on within our BB community projects as well in such a format.
We could maybe combine all our efforts?
Opinions?

**Comment by paulio** [comment]
I'd like to introduce a test-using-saved-transcripts module but I've no idea how to start contributing

**Comment by garypretty** [comment]
Closing this - I will continue some discussions with the PG to get some public facing stand ups started soon hopefully.
