### ISSUE TITLE
Issue with integrating the Alexa Adapter

### ISSUE THREAD

**Issue by aishwaryaumachandran** [BotBuilderCommunity/botbuilder-community-dotnet#323]
Hello, 

I'm trying to integrate the Alexa Adapter which was previously working. There has been an error and I not able to invoke the skill. The alexa sdk version that is being used is **4.3.53** 

The error message on the console is below:

**System.NullReferenceException: Object reference not set to an instance of an object.
   at Bot.Builder.Community.Adapters.Alexa.Helpers.PemHelper.<>c.<ParseSujectAlternativeNames>b__3_0(X509Extension ext)**

Any leads on this issue is appreciated. Thanks 

PS: We will be migrating to the Bot framework SDK 4.8 and move to the Alexa Bot Framework channel at some point. But I still wanted to get the custom adapter working at the moment

**Comment by garypretty** [comment]
Hi. The version of the adapter that you are using, due to the dependent SDK version, is very out of date and it has since been significantly refactored, including the removal of this code.  If you are looking to just have the adapter working in a development / test environment then you could consider setting ValidateIncomingAlexaRequests to false in the Alexa options, which should force the adapter to skip the validation check (which is what this code is doing).

As you have said you will be doing, I would highly recommend that you upgrade the version of the adapter as soon as you can. Thanks.

**Comment by garypretty** [comment]
Closing this as there has been no further update.
