### ISSUE TITLE
Waterfall dialog is not supported in Zoom Adapter

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [BotBuilderCommunity/botbuilder-community-dotnet#340]
My bot implements waterfall dialog where maindialog launches the waterfall dialog, it executes first step and when user replies, it suppose to go to next step in the waterfall dialog, it does not. It seems to be Dialog stack is not correctly managed.
User: Hi
MainDialog : 
   - SampleOnboardingDialog : What is your name?
  User: David
 MainDialog: Replies
Expected result is that message should be routed to correct dialog in the dialog stack (It should be SampleOnboardingDialog in this case)
 
Is it a known issue or something am I missing here? Any feedback is greatly appreciated.

**Comment by arafattehsin** [comment]
Hi @SonOfJesseAsSnekithan - Please have a look at this [sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/05.multi-turn-prompt) for your information. Since this issue is not related specifically to the Zoom adapter therefore I am closing it. Please re-open if you encounter any issue (or unexpected) behavior for the adapter.

**Comment by SonOfJesseAsSnekithan** [comment]
I am sorry, I don't get it, same code works fine for Teams and Slack channel, but only Zoom I see this behavior.
