### ISSUE TITLE
Can't find nuget package for Twilio Adapter

### ISSUE THREAD

**Issue by miguelhughes** [BotBuilderCommunity/botbuilder-community-dotnet#469]
Hi!
 I see in the source code that twilio adapter has been migrated to this repo, (#461) but when I search for Bot.Builder.Community.Adapters.Twilio on NuGet, no results show up. 
Moreover, on the readme for this repo, there's a [link to the package for twilio adapter on NuGet](https://www.nuget.org/packages/Bot.Builder.Community.Adapters.Twilio/), but the link is broken.

Is pulling the source code and building the source code locally the only way to use that adapter currently?

Thanks in advance

**Comment by ahmetkocadogan** [comment]
Hello @miguelhughes 

Is this what you are looking for?

https://www.nuget.org/packages/Microsoft.Bot.Builder.Adapters.Twilio/

**Comment by rvinothrajendran** [comment]
@miguelhughes Bot.Builder.Community.Adapters.*  Nuget package will be released soon.

**Comment by miguelhughes** [comment]
Thanks @rvinothrajendran and @ahmetkocadogan , and sorry for raising a GH issue on such a silly matter, but the thing is I'm troubleshooting an [issue on that repo](https://github.com/microsoft/botbuilder-dotnet/issues/6202) related to TwilioAdapter, and I was suggested I followup on that issue here. It seems things related to that adapter are in a state of flux. Suggestions?

**Comment by ahmetkocadogan** [comment]
@miguelhughes hello. 

First, disclaimer, i have never used twilio adapter before and honestly don't know how it works.  And i am only a user of bot framework, i develop bots with it since bot framework came out as a beta release. And i don't have any ties with Microsoft, so don't get my response as an official response.

My suggestion for you is, if it is urgent to fix your issue, fork the code, get rid of the nuget package for twilio and replace it with your class library that you copied and modified from this repo. It should be an API or SDK wrapper after all, handling webhooks and converts them to activities and handles activities to convert them to the objects required to send to twilio.

You can do whatever you like with your implementation. 

And honestly, sending proactive messages is a bit out of context for this external adapters in my opinion. Because most of the time you don't need a bot to send proactive messages, in fact the thing you want to do is related to send an sms to a number if i understand correctly, and you can use SDK's of the service that you use, in this case Twilio, by creating another controller/endpoint in your code and do the stuff there.

**Comment by miguelhughes** [comment]
@ahmetkocadogan thanks for your thought out response. You went beyond what I had linked to get a full context for a helpful response. That is really cool.
Yes, I'm willing to do that, use my own version of the adapter and remove the nuget package. I did give that a shot, but I ran into the Object disposed problem all the same. It seemed to be up the chain in the base BotAdapter so I left it at that and chose to rise that GH issue instead. 

I'm interested in your opinion, that proactive messages could be sent directly without the adapter, and I agree. But In my first message to the user I'm trying to start a conversation with a set of dialogs (questions and answers). It's not a simple out of bound message, but a start of dialog with its subsequent dialogs when the user answers. Something like [this](https://stackoverflow.com/a/56449284/1574861)
Do you think that in this case it is justified to use the bot to send the proactive message?

**Comment by ahmetkocadogan** [comment]
@miguelhughes hello.

I'm just thinking out loud here.

So, when a user sends something, you can receive the message and begin the dialog , right ? So, how do you receive that message? Twilio sends a webhook to your endpoint, adapter converts the webhook to an activity and process continues with bot and you can start a dialog.

So, for this proactive functionality, we can think a solution like this. 

First, we can create a new endpoint, for our proactive message. We send a post request to our endpoint, our endpoint creates an activity and handoff the activity to the bot, then in the bot we can seperate activities by looking at their properties about where are they coming from. If this is an activity that comes from Twilio adapter, we do our thing. If the activity is coming from our own endpoint, then we again begin the dialog just like the first senario.

Btw i never needed to send the first message from bot to user, i always want my users to contact with the bot and then i store that conversation referance for next messages that i need to send. So me thinking out loud can be wrong here, if it is, sorry about that :)

**Comment by miguelhughes** [comment]
@ahmetkocadogan Thanks so much, and sorry for my late response.
I like your approach, this is an elegant solution. 
As I commented on the original issue, thanks to your help I was able to send the proactive message from the twilio adapter. Using a different overload did the trick.
I'm a bit tight on time, but when I get to it I will try to migrate to using your approach. Thanks again for your suggestion and help so far. You rock🤘

**Comment by ahmetkocadogan** [comment]
@miguelhughes glad to help :)

you can inspect the adapter i created when you want to create your very own twilio adapter, here : 
https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.MessageBird

this may guide you to write your twilio adapter. It is basically a convertor from activity and to activity.
