### ISSUE TITLE
Webex Adapter: send messages in markdown format, too

### ISSUE THREAD

**Issue by patatofries** [BotBuilderCommunity/botbuilder-community-dotnet#479]
Hi all,

I sent markdown-formatted messages via the Webex Adapter, but they don't appear formatted. Webex expects formatted messages to be sent via the additional "markdown"-parameter, per [their API docs](https://developer.webex.com/docs/api/v1/messages/create-a-message).

To me, it looks like this functionality is prepared in the Webex Adapter Code (see [WebexMessageRequest.cs](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Webex/WebexMessageRequest.cs), property Markdown) -- but not used in the code, e.g. in [WebexClientWrapper.cs, line 127f](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/cccc14f6f598f7ddf493ebbe42e4ba40126d19fd/libraries/Bot.Builder.Community.Adapters.Webex/WebexClientWrapper.cs#L127).

My question is: how can I as a user of the Webex Adapter sent markdown-formatted messages?
If not possible yet, I would propose to sent the same message within the _text_ and _markdown_ parameter as an easy fix.

**Comment by patatofries** [comment]
My understanding of required code adaption (as Webex Client not-markdown-capable will just use the _text_ property for displaying - for all others the _markdown_ has priority over _text_
```
var request = new WebexMessageRequest
            {
                RoomId = target == MessageTarget.SpaceId ? recipient : null,
                ToPersonId = target == MessageTarget.SpaceId ? null : recipient,
                Text = text ?? string.Empty,
++           Markdown = text ?? string.Empty,
                Attachments = attachmentsContent.Count > 0 ? attachmentsContent : null,
            };
```

**Comment by bastian-thiede** [comment]
Hi,

I can confirm this issue exists. However, just adding the markdown and the text might not be sufficient. I would suggest, we handle the `MessageTextType` properly and supply the markdown only if the `MessageTextType` matches Markdown. In this case, we should provide an alternative Text without markup for `Text`. From the (API documents)[https://developer.webex.com/docs/api/v1/messages/create-a-message]:

> The message, in plain text. If `markdown` is specified this parameter may be optionally used to provide alternate text for UI clients that do not support rich text.

If my understanding is correct, we can make use of the `Bot.Builder.Community.Adapters.Shared.MarkdownToPlaintextRenderer` for this. We will further need to take a look at [`SensActivitiesAsync`](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/cccc14f6f598f7ddf493ebbe42e4ba40126d19fd/libraries/Bot.Builder.Community.Adapters.Webex/WebexAdapter.cs#L74) since `Activity.TextFormat` gets ignored here anyway and `MessageTextType` is always set to `Text`.

I might be able to work on a PR during the day or tomorrow.

**Comment by patatofries** [comment]
Hello Bastian, your Pull Request #480 matches my problem description perfectly.
Thus I will close this issue
